### PR TITLE
Adding product

### PR DESCRIPTION
**Pull request by bond15**

### CODE REVIEW

**Comment by vcvpaiva** [comment]
this is not the product?

**Comment by vcvpaiva** [comment]
the category DialSets does not have a "par" connective, the operation can be defined (as you have it) but it's not a bifunctor, I think.

**Comment by vcvpaiva** [comment]
hi,
this bit of code is not right:
+_⅋_ : DialSet → DialSet → DialSet
+(U ⋆ X ⇒2∋ α) ⅋ (V ⋆ Y ⇒2∋ β) = 
+    (U × V) ⋆ 
+    X ⊎ Y ⇒2∋
+    λ{ ((u , v) , inj₁ x) → α (u , x)
+     ; ((u , v) , inj₂ y) → β (v , y)}

we do not have a "par" connective in DialSets.

**Comment by bond15** [comment]
I thought this matched the comment here. Or is this a different operation?

_×ₚ_ : DialSet → DialSet → DialSet
a ×ₚ b = record { U × V ; X + Y; choose(alpha, beta) }
-- want to choose a relation for a pair ((u,v), s), where s= (x, o) or (y, 1). if s=(x, 0) choose  alpha, otherwise choose beta

**Comment by bond15** [comment]
the `x\_p` name is an artifact from Poly.agda

**Comment by vcvpaiva** [comment]
This is indeed a different operation, not par=multiplicative disjunction,
but oplus=additivie disjunction, which also is not a connective in DialSets.
maybe we could have a 15 min chat?

**Comment by bond15** [comment]
I'm available now. I can email a zoom link

**Comment by vcvpaiva** [comment]
please do send the zoom link

**Pull request merged**
